name: qr
version: 3.1.0-wip
description: >-
  A QR code generation library for Dart and Flutter.
  Supports QR code version 1 through 40, error correction and redundancy.
repository: https://github.com/kevmoo/qr.dart

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.7.0

dev_dependencies:
  args: ^2.1.0
  benchmark_harness: ^2.0.0
  build_runner: ^2.2.1
  build_web_compilers: ^4.1.4
  dart_flutter_team_lints: ^3.0.0
  path: ^1.9.1
  stream_transform: ^2.0.0
  test: ^1.21.6
  test_process: ^2.1.1
  web: ^1.1.0
