name: qr
version: 1.0.1
author: Kevin Moore <github@j832.com>
description: >-
  A QR code generation library for Dart and Flutter.
  Supports QR code version 1 through 40, error correction and redundancy.
homepage: https://github.com/kevmoo/qr.dart/

environment:
  sdk: '>=2.0.0-dev.17 <3.0.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  test: ^1.0.0
