name: qr
version: 3.0.2
description: >-
  A QR code generation library for Dart and Flutter.
  Supports QR code version 1 through 40, error correction and redundancy.
repository: https://github.com/kevmoo/qr.dart

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.1
  build_web_compilers: ^4.0.8
  dart_flutter_team_lints: ^3.0.0
  stream_transform: ^2.0.0
  test: ^1.21.6
  web: ^1.0.0
