name: qr
version: 1.3.0
description: >-
  A QR code generation library for Dart and Flutter.
  Supports QR code version 1 through 40, error correction and redundancy.
homepage: https://github.com/kevmoo/qr.dart/

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^2.9.0
  pedantic: ^1.0.0
  stream_transform: ^1.0.0
  test: ^1.5.0
