name: qr
version: 0.1.0+1
author: Kevin Moore <github@j832.com>
description: A library for generating QR codes in Dart.
homepage: https://github.com/kevmoo/qr.dart/

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  bot: ^0.28.0
  test: ^0.12.13

transformers:
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
    - --dump-info
    - --no-frequency-based-minification
    - --trust-type-annotations
    - --trust-primitives
